#include <set>
#include <string>
#include <vector>
#include <fstream>
#include "llvm/Pass.h"
#include "llvm/Passes/PassBuilder.h"
#include "llvm/Passes/PassPlugin.h"
// #include "llvm/Transforms/IPO/PassManagerBuilder.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/Module.h"
// #include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/InlineAsm.h"

#define CALLTRACER "tracecall"
#define RETTRACER "traceret"
#define INDIRECTBRTRACER "traceindirectbr"
#define CFBUFINITER "init_cfbuf"
#define CFBUFPURER "pure_cfbuf"

#define EDGE_FUNCLIST_FILE "passhelper.edge.funclist"
#define EXIT_FUNCLIST_FILE "passhelper.exit.funclist"
#define SKIP_FUNCLIST_FILE "passhelper.skip.funclist"

#define NO_OPAQUE_POINTER true

#ifndef DEBUG_TYPE
#define DEBUG_TYPE "tracer-pass"
#endif

namespace llvm {

class TracerPass : public PassInfoMixin<TracerPass> {
public:
	StringRef getPassName(){
		return "Tracer Instrumentation Pass";
	}
	static bool isRequired() {return true;}

	PreservedAnalyses run(Module &module, ModuleAnalysisManager &);

	bool doTrace(Function &FF);

	void instrumentCall(Module &module, CallInst &CI);
	void instrumentRet(Module &module, ReturnInst &RI);
	void instrumentIndirectBr(Module &module, IndirectBrInst &IBI);
	void instrumentEdgeFunc(Module &module, Function &F);
	// void instrumentExitFunc(Module &module, Function &F);

	// judge at the begin of doTrace() if the function is not to be instrumented
	bool isSkipInstrumentation(Function* currFunc){
		StringRef currFuncNameStr = currFunc->getName();

		// skip function declaration
		if (currFunc->isDeclaration()){
			return true;
		}
		if(skip_funcs.count(currFuncNameStr.str())){ //finded the func in skip list
			LLVM_DEBUG(dbgs() << "Skip listed func: " << currFuncNameStr << "\n");
			return true;
		}
		// skip intrinsic functions
		if (currFunc->isIntrinsic()){
			LLVM_DEBUG(dbgs() << "Skip this intrinsic: " << currFuncNameStr << "\n");
			return true;
		}

		LLVM_DEBUG(dbgs() << currFuncNameStr << " instrumenting......\n");
		return false;
	}

	// read func list generated by EdgeFuncListGenerator
	void readEdgeFuncList(){
		std::ifstream edge_file(EDGE_FUNCLIST_FILE);
		if (edge_file.is_open()){
			std::string line;
			while (getline(edge_file, line)) {
            	edge_funcs.insert(line);
        	}
			LLVM_DEBUG(dbgs() << "Number of functions in "<< EDGE_FUNCLIST_FILE << ": " << edge_funcs.size() << "\n");
		}
		else{
			LLVM_DEBUG(dbgs() << "Edge FuncList not found: "<< EDGE_FUNCLIST_FILE << "\n");
			// errs() << "Edge FuncList not found.\n";
			// throw std::runtime_error("Edge FuncList not found.");
			edge_funcs.insert("main");  // default main
		}
		return;
	}

	// read func list generated by ExitFuncListGenerator
	void readExitFuncList(){
		std::ifstream exit_file(EXIT_FUNCLIST_FILE);
		if (exit_file.is_open()){
			std::string line;
			while (getline(exit_file, line)) {
				exit_funcs.insert(line);
			}
			LLVM_DEBUG(dbgs() << "Number of functions in "<< EXIT_FUNCLIST_FILE << ": " << exit_funcs.size() << "\n");
		}
		else{
			LLVM_DEBUG(dbgs() << "Exit FuncList not found: "<< EXIT_FUNCLIST_FILE << "\n");
			// errs() << "Exit FuncList not found.\n";
			// throw std::runtime_error("Exit FuncList not found.");
			exit_funcs.insert("main");  // default main
		}
		return;
	}

	void readSkipFuncList(){
		std::ifstream skip_file(SKIP_FUNCLIST_FILE);
		if (skip_file.is_open()){
			std::string line;
			while (getline(skip_file, line)) {
				skip_funcs.insert(line);
			}
			LLVM_DEBUG(dbgs() << "Number of functions in skip.funclist: " << skip_funcs.size() << "\n");
		}
		else{
			LLVM_DEBUG(dbgs() << "Skip FuncList not found: skip.funclist\n");
			// errs() << "Skip FuncList not found.\n";
			// throw std::runtime_error("Skip FuncList not found.");
			skip_funcs.insert("tracecall");
			skip_funcs.insert("traceret");
			skip_funcs.insert("traceindirectbr");
			skip_funcs.insert("init_cfbuf");
			skip_funcs.insert("pure_cfbuf");
			skip_funcs.insert("flush_cfbuf");
			skip_funcs.insert("cflow_logger");
		}
		return;
	}

	// find an exsisting DebugLoc based on the passed inst (and look behind from it recursively).
	// the candidateDL is a cache for last updating in case of no DebugLoc found at this time.
	DebugLoc updateCandidateDL(Instruction* inst){
		DebugLoc findedDL = inst->getDebugLoc();
		auto prevInst = inst->getPrevNonDebugInstruction();
		BasicBlock* prevBB = inst->getParent()->getPrevNode();
		if (findedDL){
			return findedDL;
		}
		else if (!prevInst && !prevBB){
			return DebugLoc();
		}
		else if (!prevInst) {
			return updateCandidateDL(prevBB->getTerminator());
		}
		else if (!prevInst->getDebugLoc()){
			return updateCandidateDL(prevInst);
		}
		else{
			return prevInst->getDebugLoc();
		}
	}

	// try to add a fake debug location same as pre-instruction's.
	void addCandidateDL(CallInst* tc, DebugLoc &candidateDL){
		if (!tc->getDebugLoc()){
			if (updateCandidateDL(tc)){
				candidateDL = updateCandidateDL(tc);
			}
			tc->setDebugLoc(candidateDL);
			LLVM_DEBUG(dbgs() << "Set fake DL: " << candidateDL << " \n");
		}
	}

	FunctionCallee get_trace_flow_call_func(Module &module){
		LLVMContext &CTX = module.getContext();
		FunctionType *traceCallFuncTy = FunctionType::get(
			Type::getVoidTy(CTX), {PointerType::getUnqual(CTX)}, false);
		FunctionCallee trace_flow_call = module.getOrInsertFunction(CALLTRACER, traceCallFuncTy);
		assert(trace_flow_call);
		return trace_flow_call;
	}
	FunctionCallee get_trace_flow_ret_func(Module &module){
		LLVMContext &CTX = module.getContext();
		FunctionType *traceRetFuncTy = FunctionType::get(
			Type::getVoidTy(CTX), {PointerType::getUnqual(CTX)}, false);
		FunctionCallee trace_flow_ret = module.getOrInsertFunction(RETTRACER, traceRetFuncTy);
		assert(trace_flow_ret);
		return trace_flow_ret;
	}
	FunctionCallee get_trace_flow_indirectbr_func(Module &module){
		LLVMContext &CTX = module.getContext();
		FunctionType *traceIndirectbrFuncTy = FunctionType::get(
			Type::getVoidTy(CTX), {PointerType::getUnqual(CTX)}, false);
		FunctionCallee trace_flow_indirectbr = module.getOrInsertFunction(INDIRECTBRTRACER, traceIndirectbrFuncTy);
		assert(trace_flow_indirectbr);
		return trace_flow_indirectbr;
	}
	FunctionCallee get_first_flush_func(Module &module){
		LLVMContext &CTX = module.getContext();
		FunctionType *firstFlushFuncTy = FunctionType::get(
			Type::getVoidTy(CTX), { }, false);
		FunctionCallee first_flush = module.getOrInsertFunction(CFBUFINITER, firstFlushFuncTy);
		assert(first_flush);
		return first_flush;
	}
	FunctionCallee get_last_flush_func(Module &module){
		LLVMContext &CTX = module.getContext();
		FunctionType *lastFlushFuncTy = FunctionType::get(
			Type::getVoidTy(CTX), { }, false);
		FunctionCallee last_flush = module.getOrInsertFunction(CFBUFPURER, lastFlushFuncTy);
		assert(last_flush);
		return last_flush;
	}
	std::set<std::string> edge_funcs;
	std::set<std::string> exit_funcs;
	std::set<std::string> skip_funcs;
private:

	StringRef passtag = "att-sfi";
	StringRef instTag = "isInstrumented";
	StringRef toTrace = "toTrace";

};

// class LegacyTracerPass: public ModulePass{
// public:
// 	static char ID;
// 	LegacyTracerPass() : ModulePass(ID) {}

// 	bool runOnModule(Module &M) override;
// 	void getAnalysisUsage(AnalysisUsage &AU) const override;
// 	TracerPass tracerPassImpl;
// };


}
